name: Nagorik frontend  Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy via SSH
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          IP: ${{ secrets.IP }}
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no -p "$PORT" "$USERNAME@$IP" << EOF
            sudo su

            cd /home/alwyzon/donation-app/ncp-donation-app

            # Stop the correct PM2 process (by name)
            pm2 stop donation-app || echo "Service not running"

            # Pull the latest changes
            git pull

            # Install new dependencies if any
            npm install --legacy-peer-deps

            # Restart the PM2 process (by name)
            pm2 restart donation-app

            # Save PM2 state to persist after reboot
            pm2 save
          EOF
